#!/bin/bash
###############################################################
#	Created by Richard Tirtadji
#
#
# PHPMyAdmin installer for Raspbian Buster
# Basic script for server
###############################################################
version=`php -r "echo substr(PHP_VERSION, 0, 3);"`

MYSQLPASSWORD="$(cat ~/.mysqlrootpass)"

AUTOGENERATED_PASS="$(openssl rand -base64 14)"

export DEBIAN_FRONTEND=noninteractive

debconf-set-selections <<< "phpmyadmin phpmyadmin/reconfigure-webserver multiselect none"
debconf-set-selections <<< "phpmyadmin phpmyadmin/dbconfig-install boolean true"
debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/admin-user string root"
debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/admin-pass password $MYSQLPASSWORD"
debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/app-pass password $AUTOGENERATED_PASS"
debconf-set-selections <<< "phpmyadmin phpmyadmin/app-password-confirm password $AUTOGENERATED_PASS"

apt-get install -y phpmyadmin

cat <<EOF >/etc/phpmyadmin/nginx.conf
location /krDbAdmin {

    root /usr/share/;
    index index.php index.html index.htm;

    location ~ (.+\.php)\$ {

        #Do not remove this block. It is used by KRDesigns to set IP based restrictions
        #IP restriction start
        #allow 127.0.0.1;
        #allow 103.78.114.21;
        #IP restriction end
        #deny all;

        try_files \$uri = 404;
        include /etc/nginx/fastcgi_params;
        # To access SquirrelMail, the default user (like www-data on Debian/Ubuntu) must be used
        #fastcgi_pass 127.0.0.1:9000;
        fastcgi_pass unix:/var/run/php/php$version-fpm.sock;
        fastcgi_index index.php;
        fastcgi_intercept_errors on;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        fastcgi_buffer_size 128k;
        fastcgi_buffers 256 4k;
        fastcgi_busy_buffers_size 256k;
        fastcgi_temp_file_write_size 256k;
    }

    location ~* /.svn/ {
        deny all;
    }

    location ~* /README|INSTALL|LICENSE|SQL|bin|CHANGELOG|setup$ {
        deny all;
    }
}
EOF

ln -s /usr/share/phpmyadmin /usr/share/krDbAdmin

rm ~/.mysqlrootpass

cat <<EOF >~/.mysql_phpmyadmin_pass
MySQL root password = $MYSQLPASSWORD
phpMyAdmin password = $AUTOGENERATED_PASS
EOF

sed -n '2p' /var/lib/phpmyadmin/blowfish_secret.inc.php >> /etc/phpmyadmin/config.inc.php

service nginx restart
service php7.2-fpm restart

echo -e "Your mySQL root password is \e[32m $MYSQLPASSWORD \033[0m"
echo -e "Your phpMyAdmin root password is \e[32m $MYSQLPASSWORD \033[0m"
echo -e "phpmyadmin installation \e[32m[DONE]\033[0m"